Commit terraform

diff --git a/terraform/envs/dev/gitcom b/terraform/envs/dev/gitcom
--- a/terraform/envs/dev/gitcom
+++ b/terraform/envs/dev/gitcom
@@ -1,6 +1,11 @@
 #!/bin/bash
 
 
+if [ -z "$1" ]; then
+	echo "Commit message can't be empty"
+	exit 1
+fi
+
 git add .
-git commit -m "Commit"
+git commit -m "$1"
 git push origin main
